# Generated by Django 6.0.8 on 2026-09-22 22:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_user_failed_logins_user_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='ativo')),
                ('metodo', models.CharField(blank=True, choices=[('APP', 'Aplicativo autenticador'), ('EMAIL', 'E-mail')], default='', max_length=10, verbose_name='método')),
                ('totp_secret', models.CharField(blank=True, default='', max_length=64)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('email_codigo_hash', models.CharField(blank=True, default='', max_length=128)),
                ('email_codigo_expira', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'configuração de MFA',
                'verbose_name_plural': 'configurações de MFA',
            },
        ),
        migrations.CreateModel(
            name='CodigoRecuperacaoMFA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('codigo_hash', models.CharField(max_length=128)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacao_mfa', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'código de recuperação de MFA',
                'verbose_name_plural': 'códigos de recuperação de MFA',
                'indexes': [models.Index(fields=['user', 'usado_em'], name='contas_codi_user_id_5c067d_idx')],
            },
        ),
    ]
