# Generated by Django 6.0.8 on 2026-09-22 23:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contas', '0005_configuracaomfa_codigorecuperacaomfa'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_unico_sem_caixa', violation_error_message='Já existe uma conta com este e-mail.'),
        ),
    ]
