# Generated by Django 6.0.8 on 2026-09-24 15:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_user_user_email_unico_sem_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelDeAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='descrição')),
                ('sistema', models.BooleanField(default=False, help_text='Níveis embutidos (Aluno, Autor, Admin) não podem ser removidos.', verbose_name='nível de sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nível de acesso',
                'verbose_name_plural': 'níveis de acesso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=64, unique=True, verbose_name='código')),
                ('rotulo', models.CharField(max_length=160, verbose_name='rótulo')),
                ('modulo', models.CharField(db_index=True, max_length=32, verbose_name='módulo')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'permissão',
                'verbose_name_plural': 'permissões',
                'ordering': ['modulo', 'ordem', 'codename'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='nivel_de_acesso',
            field=models.ForeignKey(blank=True, help_text='Define as permissões granulares. Um ADMIN ignora este campo e pode tudo; sem nível, cai nas permissões padrão do papel.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='contas.niveldeacesso', verbose_name='nível de acesso'),
        ),
        migrations.AddField(
            model_name='niveldeacesso',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='niveis', to='contas.permissao', verbose_name='permissões'),
        ),
    ]
