# Generated by Django 6.0.8 on 2026-09-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_seed_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveldeacesso',
            name='acesso_admin',
            field=models.BooleanField(default=False, help_text='Usuários neste nível podem abrir o /admin. É o que define quem é administrador da plataforma.', verbose_name='acesso ao painel admin'),
        ),
    ]
