# Generated by Django 6.0.8 on 2026-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_sync_catalogo_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Usada para confirmar a idade mínima no cadastro.', null=True, verbose_name='data de nascimento'),
        ),
    ]
