# Generated by Django 6.0.8 on 2026-09-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0012_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_pendente",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Endereço pedido na troca de e-mail, ainda não confirmado pelo endereço atual. Login e 2FA seguem no e-mail atual até lá.",
                max_length=254,
                verbose_name="e-mail pendente",
            ),
        ),
    ]
