# Generated by Django 6.0.8 on 2026-09-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0013_user_email_pendente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nivel_de_acesso",
            field=models.ForeignKey(
                blank=True,
                help_text="Define as permissões granulares, admin inclusive; sem nível, cai nas permissões padrão do papel.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="contas.niveldeacesso",
                verbose_name="nível de acesso",
            ),
        ),
    ]
