# Generated by Django 6.0.8 on 2026-09-21 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trilhas', '0003_trilha_resumo_trilha_sobre_alter_trilha_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacaoDeCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(choices=[('PYTHON', 'Python')], default='PYTHON', max_length=10, verbose_name='linguagem')),
                ('funcao', models.CharField(max_length=60, verbose_name='função')),
                ('codigo_inicial', models.TextField(blank=True, default='', verbose_name='código inicial')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('exercicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacao_codigo', to='trilhas.exercicio', verbose_name='exercício')),
            ],
            options={
                'verbose_name': 'especificação de código',
                'verbose_name_plural': 'especificações de código',
            },
        ),
        migrations.CreateModel(
            name='CasoDeTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('argumentos', models.JSONField(default=list, verbose_name='argumentos')),
                ('esperado', models.JSONField(blank=True, null=True, verbose_name='retorno esperado')),
                ('erro_esperado', models.CharField(blank=True, default='', max_length=60, verbose_name='erro esperado')),
                ('visivel', models.BooleanField(default=False, verbose_name='visível')),
                ('especificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='correcao.especificacaodecodigo', verbose_name='especificação')),
            ],
            options={
                'verbose_name': 'caso de teste',
                'verbose_name_plural': 'casos de teste',
                'ordering': ['especificacao', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('especificacao', 'ordem'), name='caso_ordem_unica')],
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('EXECUTAR', 'Executar'), ('ENVIAR', 'Enviar')], max_length=10, verbose_name='modo')),
                ('codigo', models.TextField(verbose_name='código')),
                ('hash', models.CharField(db_index=True, max_length=64, verbose_name='hash')),
                ('veredito', models.CharField(choices=[('APROVADO', 'Aprovado'), ('RESPOSTA_ERRADA', 'Resposta errada'), ('TEMPO_ESGOTADO', 'Tempo esgotado'), ('ERRO_DE_EXECUCAO', 'Erro de execução')], max_length=20, verbose_name='veredito')),
                ('resultado', models.JSONField(default=dict, verbose_name='resultado')),
                ('em_cache', models.BooleanField(default=False, verbose_name='veio do cache')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('exercicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissoes', to='trilhas.exercicio', verbose_name='exercício')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'submissão',
                'verbose_name_plural': 'submissões',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['user', '-criado_em'], name='submissao_user_data_idx'), models.Index(fields=['criado_em', 'em_cache'], name='submissao_cota_idx')],
            },
        ),
    ]
