# Generated by Django 6.0.8 on 2026-09-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacaodecodigo',
            name='requisitos',
            field=models.JSONField(blank=True, default=list, verbose_name='requisitos estruturais'),
        ),
    ]
