# Generated by Django 6.0.8 on 2026-09-07 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0002_seed_creatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='attribute_label',
            field=models.CharField(blank=True, default='', help_text='Nome do atributo destacado, por exemplo Força ou Lógica.', max_length=30, verbose_name='atributo'),
        ),
        migrations.AddField(
            model_name='creature',
            name='attribute_value',
            field=models.PositiveSmallIntegerField(default=0, help_text='De 0 a 5. É apenas decorativo: não altera nenhuma regra.', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='valor do atributo'),
        ),
        migrations.AddField(
            model_name='creature',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Texto do cartão na tela de escolha da criatura.', verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='creature',
            name='type_label',
            field=models.CharField(blank=True, default='', help_text='Linha curta de sabor, no formato "Domínio / Elemento".', max_length=60, verbose_name='tipo'),
        ),
    ]
