# Generated by Django 6.0.8 on 2026-09-09 13:08

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamificacao",
            "0005_alter_usercreature_options_usercreature_is_active_and_more",
        ),
        ("trilhas", "0002_exercicio_trilha"),
    ]

    operations = [
        migrations.CreateModel(
            name="XpBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="De 1.00 a 5.00. O valor 2.00 dobra o XP da trilha para quem tem esta criatura.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                        verbose_name="multiplicador",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_bonuses",
                        to="gamificacao.creature",
                        verbose_name="criatura",
                    ),
                ),
                (
                    "trilha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_bonuses",
                        to="trilhas.trilha",
                        verbose_name="trilha",
                    ),
                ),
            ],
            options={
                "verbose_name": "bônus de XP",
                "verbose_name_plural": "bônus de XP",
                "ordering": ["trilha__ordem", "creature__display_order"],
                "indexes": [models.Index(fields=["trilha"], name="xpbonus_trilha_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creature", "trilha"),
                        name="xpbonus_um_por_criatura_e_trilha",
                        violation_error_message="Esta criatura já tem um bônus nesta trilha.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("multiplier__gte", Decimal("1.00")),
                            ("multiplier__lte", Decimal("5.00")),
                        ),
                        name="xpbonus_multiplicador_na_faixa",
                        violation_error_message="O multiplicador precisa ficar entre 1.00 e 5.00.",
                    ),
                ],
            },
        ),
    ]
