# Generated by Django 6.0.8 on 2026-10-01 17:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.clas.models
import apps.clas.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('tag', models.CharField(default=apps.clas.models.gerar_tag, editable=False, help_text='Identificador público e imutável, exibido com # na frente.', max_length=8, unique=True, verbose_name='tag')),
                ('nome', models.CharField(help_text='Pode repetir entre clãs; quem distingue é a tag. Não muda.', max_length=24, validators=[apps.clas.validators.validar_nome], verbose_name='nome')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, validators=[apps.clas.validators.validar_sem_palavras_proibidas], verbose_name='descrição')),
                ('bandeira', models.CharField(choices=[('guilda_1', 'Guilda 1'), ('guilda_2', 'Guilda 2'), ('guilda_3', 'Guilda 3'), ('guilda_4', 'Guilda 4')], max_length=16, verbose_name='bandeira')),
                ('tipo', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PUBLICO', help_text='Público aparece na busca e aceita entrada direta. Privado só aceita entrada por link de convite.', max_length=10, verbose_name='tipo')),
                ('nivel_minimo', models.PositiveSmallIntegerField(default=5, help_text='Nível da criatura mais forte do usuário exigido para entrar. Nunca abaixo do mínimo global.', verbose_name='nível mínimo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'clã',
                'verbose_name_plural': 'clãs',
                'ordering': ['-criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nivel_minimo__gte', 5)), name='cla_nivel_minimo_global', violation_error_message='O nível mínimo não pode ficar abaixo do mínimo global.'), models.CheckConstraint(condition=models.Q(('bandeira__in', ['guilda_1', 'guilda_2', 'guilda_3', 'guilda_4'])), name='cla_bandeira_valida'), models.CheckConstraint(condition=models.Q(('tipo__in', ['PUBLICO', 'PRIVADO'])), name='cla_tipo_valido'), models.CheckConstraint(condition=models.Q(('tag__regex', '^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{8}$')), name='cla_tag_formato')],
            },
        ),
        migrations.CreateModel(
            name='ConviteDoCla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='hash do token')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('revogado_em', models.DateTimeField(blank=True, help_text='Preenchido ao gerar um novo link ou ao revogar este.', null=True, verbose_name='revogado em')),
                ('cla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='clas.cla', verbose_name='clã')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'convite do clã',
                'verbose_name_plural': 'convites dos clãs',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revogado_em__isnull', True)), fields=('cla',), name='convitedocla_um_ativo_por_cla', violation_error_message='Este clã já tem um convite ativo.'), models.CheckConstraint(condition=models.Q(('expira_em__gt', models.F('criado_em'))), name='convitedocla_expira_depois_de_criar')],
            },
        ),
        migrations.CreateModel(
            name='MembroDoCla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('cargo', models.CharField(choices=[('LIDER', 'Líder'), ('COLIDER', 'Co-líder'), ('MEMBRO', 'Membro')], default='MEMBRO', max_length=10, verbose_name='cargo')),
                ('entrou_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entrou em')),
                ('cla', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='clas.cla', verbose_name='clã')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membro_de_cla', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'membro do clã',
                'verbose_name_plural': 'membros dos clãs',
                'ordering': ['entrou_em'],
                'indexes': [models.Index(fields=['cla', 'cargo', 'entrou_em'], name='membrodocla_cla_cargo_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cargo', 'LIDER')), fields=('cla',), name='membrodocla_um_lider_por_cla', violation_error_message='Este clã já tem um líder.'), models.CheckConstraint(condition=models.Q(('cargo__in', ['LIDER', 'COLIDER', 'MEMBRO'])), name='membrodocla_cargo_valido')],
            },
        ),
    ]
