# Generated by Django 6.0.8 on 2026-09-09 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamificacao', '0004_seed_fichas'),
        ('trilhas', '0002_exercicio_trilha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('numero', models.PositiveSmallIntegerField(help_text='Identificador estável. O nível 1 precisa existir com 0 de XP.', primary_key=True, serialize=False, verbose_name='número')),
                ('xp_necessario', models.PositiveIntegerField(help_text='Total acumulado, não incremento. O nível 1 é sempre 0.', unique=True, verbose_name='XP acumulado necessário')),
                ('titulo', models.CharField(blank=True, default='', help_text='Rótulo exibido no perfil, por exemplo Aprendiz ou Arquiteto.', max_length=40, verbose_name='título')),
            ],
            options={
                'verbose_name': 'nível',
                'verbose_name_plural': 'níveis',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='EventoXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('EXERCICIO', 'Exercício concluído'), ('AJUSTE', 'Ajuste de progressão')], default='EXERCICIO', max_length=15, verbose_name='origem')),
                ('xp', models.PositiveIntegerField(help_text='Valor congelado no momento da concessão.', verbose_name='XP concedido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('exercicio', models.ForeignKey(blank=True, help_text='Nulo em ajustes manuais e quando o exercício é removido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_xp', to='trilhas.exercicio', verbose_name='exercício')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_xp', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('user_creature', models.ForeignKey(blank=True, help_text='A criatura ativa no momento em que o XP foi concedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_xp', to='gamificacao.usercreature', verbose_name='criatura do usuário')),
            ],
            options={
                'verbose_name': 'evento de XP',
                'verbose_name_plural': 'eventos de XP',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['user', '-criado_em'], name='eventoxp_user_data_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('origem', 'EXERCICIO')), fields=('user', 'exercicio'), name='eventoxp_um_por_exercicio_por_usuario', violation_error_message='Este exercício já concedeu XP a este usuário.')],
            },
        ),
        migrations.CreateModel(
            name='ProgressoCriatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0, help_text='Soma dos eventos desta criatura. Cache derivado de EventoXP.', verbose_name='XP total')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nivel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='progressos', to='progressao.nivel', verbose_name='nível')),
                ('user_creature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='gamificacao.usercreature', verbose_name='criatura do usuário')),
            ],
            options={
                'verbose_name': 'progresso da criatura',
                'verbose_name_plural': 'progressos das criaturas',
                'ordering': ['-xp_total'],
                'indexes': [models.Index(fields=['-xp_total'], name='progressocriatura_xp_idx')],
            },
        ),
    ]
