# Generated by Django 6.0.8 on 2026-09-12 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("progressao", "0002_seed_niveis"),
        ("trilhas", "0003_trilha_resumo_trilha_sobre_alter_trilha_descricao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrilhaIniciada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iniciada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="iniciada em"),
                ),
                (
                    "trilha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iniciadas",
                        to="trilhas.trilha",
                        verbose_name="trilha",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trilhas_iniciadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "trilha iniciada",
                "verbose_name_plural": "trilhas iniciadas",
                "ordering": ["-iniciada_em"],
                "indexes": [
                    models.Index(fields=["user"], name="trilhainiciada_user_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "trilha"),
                        name="trilhainiciada_uma_por_trilha_por_usuario",
                        violation_error_message="Esta trilha já foi iniciada.",
                    )
                ],
            },
        ),
    ]
