# Generated by Django 6.0.8 on 2026-09-21 23:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='registrado em')),
                ('actor_email_snapshot', models.CharField(blank=True, default='', help_text='Preserva quem era, mesmo após anonimizar ou excluir a conta.', max_length=254, verbose_name='e-mail do autor (no momento)')),
                ('acao', models.CharField(choices=[('LOGIN_OK', 'Login bem-sucedido'), ('LOGIN_FALHA', 'Falha de login'), ('LOGOUT', 'Logout'), ('CADASTRO', 'Conta criada'), ('EMAIL_VERIFICADO', 'E-mail verificado'), ('SENHA_REDEFINIDA', 'Senha redefinida'), ('TROCA_EMAIL_SOLICITADA', 'Troca de e-mail solicitada'), ('TROCA_EMAIL_CONFIRMADA', 'Troca de e-mail confirmada'), ('EXCLUSAO_SOLICITADA', 'Exclusão de conta solicitada'), ('ACESSO_AUDITORIA', 'Consulta à trilha de auditoria'), ('PAPEL_CONCEDIDO', 'Papel concedido'), ('PAPEL_REMOVIDO', 'Papel removido'), ('CONTA_SUSPENSA', 'Conta suspensa'), ('CONTA_REATIVADA', 'Conta reativada'), ('EXPORTACAO_DADOS', 'Exportação de dados do titular')], db_index=True, max_length=32, verbose_name='ação')),
                ('alvo_tipo', models.CharField(blank=True, default='', max_length=64, verbose_name='tipo do alvo')),
                ('alvo_id', models.CharField(blank=True, default='', max_length=64, verbose_name='id do alvo')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.CharField(blank=True, default='', max_length=256, verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexto não sensível da ação (motivo, filtros etc.).', verbose_name='metadados')),
                ('actor', models.ForeignKey(blank=True, help_text='Nulo quando anônimo ou após a exclusão do usuário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='autor da ação')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['acao', '-created_at'], name='auditoria_acao_data_idx'), models.Index(fields=['actor', '-created_at'], name='auditoria_actor_data_idx')],
            },
        ),
    ]
