# Generated by Django 6.0.8 on 2026-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_registrodeauditoria_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN_OK', 'Login bem-sucedido'), ('LOGIN_FALHA', 'Falha de login'), ('LOGOUT', 'Logout'), ('CADASTRO', 'Conta criada'), ('EMAIL_VERIFICADO', 'E-mail verificado'), ('SENHA_REDEFINIDA', 'Senha redefinida'), ('TROCA_EMAIL_SOLICITADA', 'Troca de e-mail solicitada'), ('TROCA_EMAIL_CONFIRMADA', 'Troca de e-mail confirmada'), ('EXCLUSAO_SOLICITADA', 'Exclusão de conta solicitada'), ('NICKNAME_ALTERADO', 'Nickname alterado'), ('CRIATURA_ADQUIRIDA', 'Criatura adquirida'), ('CRIATURA_EVOLUIDA', 'Criatura evoluída'), ('EXPORTACAO_DADOS', 'Exportação de dados do titular'), ('CONSENTIMENTO_ACEITO', 'Consentimento (re)aceito'), ('ACESSO_AUDITORIA', 'Consulta à trilha de auditoria'), ('CONTA_ANONIMIZADA', 'Conta anonimizada'), ('PAPEL_CONCEDIDO', 'Papel concedido'), ('PAPEL_REMOVIDO', 'Papel removido'), ('CONTA_SUSPENSA', 'Conta suspensa'), ('CONTA_REATIVADA', 'Conta reativada')], db_index=True, max_length=32, verbose_name='ação'),
        ),
    ]
