# Generated by Django 6.0.8 on 2026-10-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_registrodeauditoria_acao_troca_autorizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN_OK', 'Login bem-sucedido'), ('LOGIN_FALHA', 'Falha de login'), ('LOGOUT', 'Logout'), ('CADASTRO', 'Conta criada'), ('EMAIL_VERIFICADO', 'E-mail verificado'), ('SENHA_REDEFINIDA', 'Senha redefinida'), ('TROCA_EMAIL_SOLICITADA', 'Troca de e-mail solicitada'), ('TROCA_EMAIL_AUTORIZADA', 'Troca de e-mail autorizada'), ('TROCA_EMAIL_CONFIRMADA', 'Troca de e-mail confirmada'), ('EXCLUSAO_SOLICITADA', 'Exclusão de conta solicitada'), ('NICKNAME_ALTERADO', 'Nickname alterado'), ('CRIATURA_ADQUIRIDA', 'Criatura adquirida'), ('CRIATURA_EVOLUIDA', 'Criatura evoluída'), ('EXPORTACAO_DADOS', 'Exportação de dados do titular'), ('CONSENTIMENTO_ACEITO', 'Consentimento (re)aceito'), ('MFA_ATIVADO', 'Verificação em duas etapas ativada'), ('MFA_DESATIVADO', 'Verificação em duas etapas desativada'), ('ACESSO_AUDITORIA', 'Consulta à trilha de auditoria'), ('CONTA_ANONIMIZADA', 'Conta anonimizada'), ('NIVEL_CRIADO', 'Nível de acesso criado'), ('NIVEL_EDITADO', 'Nível de acesso editado'), ('NIVEL_REMOVIDO', 'Nível de acesso removido'), ('NIVEL_ATRIBUIDO', 'Nível de acesso atribuído a usuário'), ('CLA_CRIADO', 'Clã criado'), ('CLA_EDITADO', 'Clã editado'), ('CLA_APAGADO', 'Clã apagado'), ('CLA_ENTROU', 'Entrou em clã'), ('CLA_SAIU', 'Saiu de clã'), ('CLA_MEMBRO_PROMOVIDO', 'Membro de clã promovido'), ('CLA_MEMBRO_REBAIXADO', 'Membro de clã rebaixado'), ('CLA_MEMBRO_EXPULSO', 'Membro expulso de clã'), ('CLA_LIDERANCA_TRANSFERIDA', 'Liderança de clã transferida'), ('CLA_CONVITE_GERADO', 'Convite de clã gerado'), ('CLA_CONVITE_REVOGADO', 'Convite de clã revogado'), ('PAPEL_CONCEDIDO', 'Papel concedido'), ('PAPEL_REMOVIDO', 'Papel removido'), ('CONTA_SUSPENSA', 'Conta suspensa'), ('CONTA_REATIVADA', 'Conta reativada')], db_index=True, max_length=32, verbose_name='ação'),
        ),
    ]
