# Termos-base. Acento, maiúscula, leetspeak, letra repetida, plural e
# separadores ("f.d.p", "p0rr4") são tratados pelo validador.
# Fora de propósito: palavras com outro sentido comum (pica-pau, veado) e
# xingamento leve (idiota, burro, otário), que barrariam nome de clã normal.
PALAVRAS_PROIBIDAS: frozenset[str] = frozenset(
    {
        # palavrões
        "porra",
        "caralho",
        "caraio",
        "karalho",
        "merda",
        "bosta",
        "foder",
        "fuder",
        "foda",
        "fodase",
        "fodido",
        "fodida",
        "fudido",
        "fudida",
        "fodao",
        "cu",
        "cuzao",
        "cuzona",
        "cuzinho",
        "arrombado",
        "arrombada",
        "desgraçado",
        "desgraçada",
        "escroto",
        "escrota",
        "filho da puta",
        "filha da puta",
        # abreviações
        "fdp",
        "pqp",
        "vsf",
        "vtnc",
        "tnc",
        "tmnc",
        "pnc",
        "krl",
        "crl",
        # sexual
        "puta",
        "putinha",
        "putaria",
        "puteiro",
        "buceta",
        "boceta",
        "xoxota",
        "xereca",
        "piroca",
        "caralhudo",
        "punheta",
        "punheteiro",
        "boquete",
        "siririca",
        "vadia",
        "vagabunda",
        "biscate",
        "piranha",
        # ofensa por orientação ou identidade
        "viado",
        "viadinho",
        "bicha",
        "bichona",
        "boiola",
        "baitola",
        "sapatão",
        "traveco",
        # ofensa racial
        "crioulo",
        "crioula",
        "macaco",
        "macaca",
        "preto imundo",
        "negro imundo",
        # ofensa a pessoa com deficiência
        "retardado",
        "retardada",
        "mongoloide",
        "mongol",
        "debil mental",
        # crime e ódio
        "estupro",
        "estuprar",
        "estuprador",
        "estupradora",
        "pedofilo",
        "pedofila",
        "pedofilia",
        "nazista",
        "nazismo",
        "hitler",
        "sieg heil",
        "supremacia branca",
        "white power",
    }
)
