# Generated by Django 6.0.8 on 2026-09-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trilha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome exibido no card e no cabeçalho da trilha.",
                        max_length=80,
                        verbose_name="nome",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador usado na URL. Não renomeie sem redirecionar.",
                        max_length=80,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Resumo de uma ou duas frases, exibido no card da listagem.",
                        verbose_name="descrição",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Posição na listagem de trilhas.",
                        verbose_name="ordem",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("REVISAO", "Em revisão"),
                            ("APROVADO", "Aprovado"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=10,
                        verbose_name="status editorial",
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "atualizada_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
            ],
            options={
                "verbose_name": "trilha",
                "verbose_name_plural": "trilhas",
                "ordering": ["ordem", "nome"],
                "indexes": [
                    models.Index(
                        fields=["status", "ordem"], name="trilha_status_ordem_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="título")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Único dentro da trilha.",
                        max_length=120,
                        verbose_name="slug",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Material da aula, em Markdown.",
                        verbose_name="conteúdo",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordem"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("REVISAO", "Em revisão"),
                            ("APROVADO", "Aprovado"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=10,
                        verbose_name="status editorial",
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "atualizada_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "pre_requisito",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aula que precisa ser concluída antes desta, na mesma trilha.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependentes",
                        to="trilhas.aula",
                        verbose_name="pré-requisito",
                    ),
                ),
                (
                    "trilha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="trilhas.trilha",
                        verbose_name="trilha",
                    ),
                ),
            ],
            options={
                "verbose_name": "aula",
                "verbose_name_plural": "aulas",
                "ordering": ["ordem", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Exercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="título")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Único dentro da aula.",
                        max_length=120,
                        verbose_name="slug",
                    ),
                ),
                ("enunciado", models.TextField(verbose_name="enunciado")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("CODIGO", "Código"), ("TEORICO", "Teórico")],
                        default="CODIGO",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("INICIANTE", "Iniciante"),
                            ("INTERMEDIARIO", "Intermediário"),
                            ("AVANCADO", "Avançado"),
                        ],
                        db_index=True,
                        default="INICIANTE",
                        max_length=15,
                        verbose_name="dificuldade",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordem"),
                ),
                (
                    "solucao_autor",
                    models.TextField(
                        blank=True,
                        help_text="Solução de referência. Nunca é serializada pela API pública: só quem tem trilhas.view_solution pode ver, por rota própria.",
                        verbose_name="solução do autor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("REVISAO", "Em revisão"),
                            ("APROVADO", "Aprovado"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        db_index=True,
                        default="RASCUNHO",
                        max_length=10,
                        verbose_name="status editorial",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicios",
                        to="trilhas.aula",
                        verbose_name="aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "exercício",
                "verbose_name_plural": "exercícios",
                "ordering": ["ordem", "titulo"],
                "indexes": [
                    models.Index(
                        fields=["aula", "ordem"], name="exercicio_aula_ordem_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aula", "slug"),
                        name="exercicio_slug_unico_por_aula",
                        violation_error_message="Esta aula já tem um exercício com este slug.",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aula",
            index=models.Index(
                fields=["trilha", "ordem"], name="aula_trilha_ordem_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="aula",
            constraint=models.UniqueConstraint(
                fields=("trilha", "slug"),
                name="aula_slug_unico_por_trilha",
                violation_error_message="Esta trilha já tem uma aula com este slug.",
            ),
        ),
    ]
