# Generated by Django 6.0.8 on 2026-09-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0002_exercicio_trilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='resumo',
            field=models.TextField(blank=True, help_text='Parágrafo do topo da página da trilha. Duas ou três frases. Vazio cai na descrição.', verbose_name='resumo'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='sobre',
            field=models.TextField(blank=True, help_text='Texto da seção “Sobre a trilha”. Aceita vários parágrafos separados por linha em branco. Vazio cai no resumo.', verbose_name='sobre'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='descricao',
            field=models.TextField(help_text='Linha de catálogo, exibida truncada no card da listagem ao lado da carga horária. Frase única e curta, sem ponto final.', verbose_name='descrição'),
        ),
    ]
